### ISSUE TITLE
Wrong formula in the intercalibration of dmsp/ols

### ISSUE THREAD

**Issue by complexly** [itpir/geo-datasets#60]
In line 84 of https://github.com/itpir/geo-datasets/blob/master/dmsp_ols/processing.py, the current formula

> output_array = c0 + (tmp_array * c1) + (tmp_array ** c2) 

is not correct. It should be:

> output_array = c0 + (tmp_array * c1) + (tmp_array ** 2 * c2)

**Comment by sgoodm** [comment]
Good catch. Fixed in 1c1cc2944763083a4e8cc17cd79bfe354cbeaa7f
